apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: online-boutique
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP